server:
  port: 8080
spring:
  main:
    web-application-type: reactive
  application:
    name: Api-Gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: Bike-Service
          uri: lb://Bike-Service
          predicates:
            - Path=/api/v1/bicycles/**

        - id: Rental-Service
          uri: lb://Rental-Service
          predicates:
            - Path=/api/v1/rents/**

        - id: User-Service
          uri: lb://User-Service
          predicates:
            - Path=/api/v1/users/**

        - id: Auth-Service
          uri: lb://Auth-Service
          predicates:
            - Path=/api/v1/auth/**

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true

    service-url:
      defaultZone: http://localhost:8761/eureka

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /rental-service/v3/api-docs
        name: Rental Service
        primaryName: Rental-Service
      - url: /bike-service/v3/api-docs
        name: Bike Service
        primaryName: Bike-Service
      - url: /user-service/v3/api-docs
        name: User Service
        primaryName: User-Service
      - url: /auth-service/v3/api-docs
        name: Auth Service
        primaryName: Auth-Service

