networks:
  lyw:
services:
  lyw.db:
    container_name: lyw.db
    image: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: lywdb
      MYSQL_ROOT_PASSWORD: root
    networks:
        - lyw
  lyw.app:
    container_name: lyw.app
    image: auth-microservice:1.0
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - 8081:8080
    depends_on:
      - lyw.db
    environment:
      MYSQL_HOST: lyw.db
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3307
    restart: on-failure
    networks:
        - lyw