server:
  error:
    include-stacktrace: never
  port: ${PORT:${SERVER_PORT:0}}
openapi:
  service:
    title: LeadYourWay Rental Service API
    version: 1.0
    url: http://localhost:8080
springdoc:
  api-docs:
    path: /rental-service/v3/api-docs
  swagger-ui:
    path: /rental-service/swagger-ui.html
spring:
  application:
    name: Rental-Service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 12345678
    url: jdbc:mysql://localhost:3306/rental
    username: root
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: pe.edu.leadyourway.rentalmicroservice.infrastructure.persistence.jpa.SnakeCasePhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka