version: '3'
services:
  app:
    image: leadyourway-user
    ports:
      - "8080:8080"
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: leadyourway_user
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
